# Generated by Django 6.1 on 2026-08-10 09:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_story', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapturedPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='chapter4/captures/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('shot_mode', models.CharField(choices=[('FRONT_45', 'Front 45°'), ('SIDE', 'Side'), ('DETAIL', 'Detail')], default='FRONT_45', max_length=20)),
                ('brightness_score', models.FloatField(blank=True, null=True)),
                ('blur_score', models.FloatField(blank=True, null=True)),
                ('is_in_frame', models.BooleanField(default=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('style_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captured_photos', to='ai_story.userstyleselection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
