# Generated by Django 6.0.7 on 2026-08-19 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_story', '0009_product_image_url'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturedphoto',
            name='style_selection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captured_photos', to='ai_story.userstyleselection'),
        ),
    ]
