# Generated by Django 6.1 on 2026-08-08 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('carry', 'Carry Option'), ('detail', 'Detail Option')], max_length=20, verbose_name='옵션 그룹')),
                ('name', models.CharField(max_length=50, verbose_name='옵션 이름')),
                ('code_name', models.CharField(max_length=50, unique=True, verbose_name='식별 코드')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='제품명')),
                ('description', models.TextField(verbose_name='제품 설명')),
            ],
        ),
        migrations.CreateModel(
            name='StyleCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='조합된 제품 이미지 URL')),
                ('ai_narration', models.TextField(verbose_name='AI 내레이션 문구')),
                ('carry_option', models.ForeignKey(limit_choices_to={'group': 'carry'}, on_delete=django.db.models.deletion.CASCADE, related_name='carry_combinations', to='ai_story.option', verbose_name='캐리 옵션')),
                ('detail_option', models.ForeignKey(limit_choices_to={'group': 'detail'}, on_delete=django.db.models.deletion.CASCADE, related_name='detail_combinations', to='ai_story.option', verbose_name='디테일 옵션')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_story.product', verbose_name='제품')),
            ],
        ),
        migrations.CreateModel(
            name='UserStyleSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_narration', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carry_option', models.ForeignKey(limit_choices_to={'group': 'carry'}, on_delete=django.db.models.deletion.CASCADE, related_name='user_selected_carry', to='ai_story.option')),
                ('detail_option', models.ForeignKey(limit_choices_to={'group': 'detail'}, on_delete=django.db.models.deletion.CASCADE, related_name='user_selected_detail', to='ai_story.option')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_story.product')),
            ],
        ),
    ]
