# Generated by Django 6.1 on 2026-08-10 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_story', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My MCM Story Card', max_length=100)),
                ('card_text', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_selected', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('captured_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journey_cards', to='product.capturedphoto')),
                ('style_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_cards', to='ai_story.userstyleselection')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
