# Generated by Django 6.1 on 2026-08-10 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_story', '0002_journeycard'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeycard',
            name='share_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userstyleselection',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userstyleselection',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='HesitationReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('SIZE', 'Size'), ('WEIGHT', 'Weight'), ('STORAGE', 'Storage'), ('COMFORT', 'Comfort'), ('PRICE', 'Price'), ('DESIGN', 'Design')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_reconsidered_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconsideration_source', to='ai_story.journeycard')),
                ('style_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hesitation_reasons', to='ai_story.userstyleselection')),
            ],
        ),
    ]
