# Generated by Django 6.1 on 2026-08-11 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_story', '0005_auto_20260811_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyCardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=50)),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('card_text', models.TextField()),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='journey_templates/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='journeycard',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journey_cards', to='ai_story.journeycardtemplate'),
        ),
    ]
