# Generated by Django 6.0.7 on 2026-08-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_story', '0006_journeycardtemplate_journeycard_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeycard',
            name='card_image',
            field=models.ImageField(blank=True, null=True, upload_to='journey_cards/', verbose_name='AI 합성/생성 카드 이미지'),
        ),
    ]
