# Generated by Django 6.1 on 2026-08-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_story', '0007_journeycard_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstyleselection',
            name='selected_moment',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='선택된 모먼트'),
        ),
    ]
