# Generated by Django 6.1 on 2026-08-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_story', '0008_userstyleselection_selected_moment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='제품 이미지 URL'),
        ),
    ]
