# Generated by Django 6.0.7 on 2026-08-10 16:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(help_text='예: ELLA_BOSTON_BAG', max_length=50, primary_key=True, serialize=False)),
                ('nfc_tag_id', models.CharField(max_length=100, unique=True)),
                ('qr_code_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField(max_length=500)),
                ('story_title', models.CharField(max_length=200)),
                ('story_desc', models.TextField()),
                ('is_supported', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='JourneySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_chapter', models.CharField(default='C1', max_length=10)),
                ('last_active_screen', models.CharField(default='C1-01', max_length=20)),
                ('selected_moment', models.CharField(blank=True, max_length=50, null=True)),
                ('carry_option', models.CharField(blank=True, max_length=50, null=True)),
                ('detail_option', models.CharField(blank=True, max_length=50, null=True)),
                ('photo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('chosen_story_card_id', models.CharField(blank=True, max_length=50, null=True)),
                ('hesitate_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='journey.product')),
            ],
        ),
    ]
