# Generated by Django 6.1 on 2026-08-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeysession',
            name='ai_story_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
