# Generated by Django 6.0.7 on 2026-08-17 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0002_journeysession_ai_story_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journeysession',
            name='ai_story_text',
        ),
    ]
