# Generated by Django 6.1 on 2026-08-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0003_remove_journeysession_ai_story_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeysession',
            name='generated_caption',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journeysession',
            name='generated_image',
            field=models.ImageField(blank=True, null=True, upload_to='generated/'),
        ),
    ]
